# For full Serverless config options, check the docs:
#    https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service: google-product-search-integration

# You can change this to any cloud provider:
# AWS Lambda: <https://aws.amazon.com/lambda/>
# Microsoft Azure: <https://azure.microsoft.com/en-us/overview/serverless-computing/>
# Google Cloud Functions: <https://cloud.google.com/functions/>
# IBM Cloud Functions: <https://www.ibm.com/cloud/functions/details>
#
# before you deploy your app, you should set credential with the follow cmd:
# serverless config credentials --provider aws --key $AWS_KEY$ --secret $AWS_SECRET$ -o
provider:
  name: google
  runtime: nodejs8
  project: YOUR_PROJECT_NAME
  # the path to the credentials file needs to be absolute
  credentials: ./privatekey.json
  environment:
     PROJECT_ID: CHANGE_ME
     LOCATION: CHANGE_ME
     SET_ID: CHANGE_ME

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  first:
    handler: skills
    events:
      - http: path